Feat/es6
Foodrive/graphql-server pull request #2
Opened 2021-06-22 14:26 UTC by GitAndrew

- Added babel for es6 support
- Refactored code to use es6 imports instead of commonjs require
- Added nodemon for hot loading (for dev)
- Updated package.json scripts - serve for prod, start for dev

Couple of issues I found along the way:
- Needed to add --copy-files to babel cli call (see within npm run serve) because by default babel will not compile/copy over the .graphql files into the dist folder
- Encountered an issue with babel compiling bunyan logger, needed to add the plugin: @babel/plugin-transform-runtime
https://stackoverflow.com/questions/61755999/uncaught-referenceerror-regeneratorruntime-is-not-defined-in-react

2021-06-22 14:27 UTC, GitAndrew commented on .babelrc
> +    "plugins": ["@babel/plugin-transform-runtime"]
As mentioned, needed this to for babel to compile the loggers.
https://stackoverflow.com/questions/61755999/uncaught-referenceerror-regeneratorruntime-is-not-defined-in-react

2021-06-22 14:28 UTC, GitAndrew commented on .eslintrc.js
> +  extends: ["airbnb-base", "prettier"],
Swapping these two resolved the conflicts I had for auto-formatting on save

2021-06-22 14:28 UTC, GitAndrew commented on jsconfig.json
> +}
Added this file so you can do relative imports to src in vscode

2021-06-22 14:29 UTC, GitAndrew commented on package.json
> +    "start": "nodemon --exec babel-node src/bin/www.js",
Note:
For prod: npm run serve
For dev: npm run start

babel-node is not appropriate for production: https://babeljs.io/docs/en/babel-node.html

2021-06-22 23:24 UTC, chrisrabe requested changes
Need to change the location of the main script in package.json

2021-06-22 23:24 UTC, chrisrabe commented on src/bin/www.js
> +server.listen().then(({ url }) => {
hmm might need to change the main script to src/bin/www in package.json

2021-06-23 04:24 UTC, chrisrabe approved these changes
looks good

2021-06-23 04:24 UTC, merged